# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: degoya.rDownloader
PackageVersion: 1.21.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rdownloader-capture.exe
  PortableCommandAlias: rdownloader-capture
- RelativeFilePath: rdownloader.exe
  PortableCommandAlias: rdownloader
Commands:
- rdownloader
- rdownloader-capture
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/degoya/rDownloader/releases/download/v1.21.0/rdownloader-windows-x86_64.zip
  InstallerSha256: 855D0DB680657E882204812EEC8E3DFCC1AB584F76B735D9B18413917DBF60DD
ManifestType: installer
ManifestVersion: 1.12.0
