# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: degoya.rDownloader
PackageVersion: 1.9.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rdownloader-capture.exe
  PortableCommandAlias: rdownloader-capture
- RelativeFilePath: rdownloader.exe
  PortableCommandAlias: rdownloader
Commands:
- rdownloader
- rdownloader-capture
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/degoya/rDownloader/releases/download/v1.9.1/rdownloader-windows-x86_64.zip
  InstallerSha256: 2E3BFDEF83620178C90D6F6F881449F8883638859D252FA23F1E84176BF5E28C
ManifestType: installer
ManifestVersion: 1.12.0
