# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: degoya.rDownloader
PackageVersion: 1.8.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rdownloader-capture.exe
  PortableCommandAlias: rdownloader-capture
- RelativeFilePath: rdownloader.exe
  PortableCommandAlias: rdownloader
Commands:
- rdownloader
- rdownloader-capture
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/degoya/rDownloader/releases/download/v1.8.0/rdownloader-windows-x86_64.zip
  InstallerSha256: F8AFC52172C5D8EFEBC489F784F247CC2C729F856042B357B02341E05D408D1C
ManifestType: installer
ManifestVersion: 1.12.0
