# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: degoya.rDownloader
PackageVersion: 1.10.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rdownloader-capture.exe
  PortableCommandAlias: rdownloader-capture
- RelativeFilePath: rdownloader.exe
  PortableCommandAlias: rdownloader
Commands:
- rdownloader
- rdownloader-capture
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/degoya/rDownloader/releases/download/v1.10.1/rdownloader-windows-x86_64.zip
  InstallerSha256: 8D26B5EFC1676D52B14DF987BCF6F44F29C74E12DCCD79C0732D68E87BF5F0F5
ManifestType: installer
ManifestVersion: 1.12.0
