# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: degoya.rDownloader
PackageVersion: 1.23.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rdownloader-capture.exe
  PortableCommandAlias: rdownloader-capture
- RelativeFilePath: rdownloader.exe
  PortableCommandAlias: rdownloader
Commands:
- rdownloader
- rdownloader-capture
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/degoya/rDownloader/releases/download/v1.23.0/rdownloader-windows-x86_64.zip
  InstallerSha256: 4E1D03CCD0424A8D92E468406DB2D9D97518C4D9EF28CF74D4741C69E2BAB732
ManifestType: installer
ManifestVersion: 1.12.0
